### ISSUE TITLE
Awakari is posting back duplicated content into ActivityPub

### ISSUE THREAD

**Issue by renchap** [awakari/webapp#4]
For example, when opening https://mastodon.social/@fediverse@activitypub.awakari.com/112869943577652193 on mastodon.social, I see this:
<img width="601" alt="image" src="https://github.com/user-attachments/assets/a0304a0a-8204-4084-b429-8056b92cba58">

This status is public, meaning that its content is indexed and if you follow one of the hashtags, it will appear in your feed. It kind of impersonates the initial status and creates a lot of duplicated content.

Please do not do this. If you want something similar, you could set the status privacy to followers only, so people can opt into viewing those by following the `@fediverse@activitypub.awakari.com` account?

If you do not solve this issue, expect your server to be limited/blocked on many instances (including mastodon.social).

**Comment by akurilov** [comment]
@renchap thank you for reporting this. I will fix it in the corresponding repo: https://github.com/awakari/int-activitypub

**Comment by akurilov** [comment]
fix proposal: https://github.com/awakari/int-activitypub/commit/97c0860bb9ea9cb54c911e8672df788069c17471#diff-db464cbcca7777d1ddca562372e0a9c867dbd0b991301dd776c721784977f48bR521

**Comment by renchap** [comment]
This repository is not public, so I can not check it

**Comment by akurilov** [comment]
I think the fix works
![2024-07-30_23-19](https://github.com/user-attachments/assets/791a3dcf-b49d-4f0a-a48a-5a21148cab0b)
Also, the repo is now public

**Comment by renchap** [comment]
It looks like this behaviour is back and polluting people's feed again, for example https://mastodon.social/@Kubernetes@activitypub.awakari.com is full of public posts.
